#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
lyx_to_tex — translate math insets in a LyX document into ``_tex`` UDL
invocations consumable by the ``tensor::tex`` parser.

Realises ADR-0005's "LyX as a first-class authoring surface" promise.
LyX users write math in WYSIWYG mode; this script extracts every
``\\begin_inset Formula ... \\end_inset`` block and prints a C++ snippet
that wraps the inset body in ``R"(...)" _tex`` so the same string lands
in the ``tensor::tex::Expression`` AST.

Status: MVP. Only inline ``$...$`` and display ``\\[ ... \\]`` formulas
are recognised; richer LyX insets (LyX-Code, ERT, custom modules) fall
through unchanged. The output is suitable as input to the
``tensor::tex::Evaluator``.

Usage:
    python lyx_to_tex.py path/to/document.lyx [--namespace tensor::tex::literals]
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List


# The LyX inset header line is "\begin_inset Formula" followed by the
# delimited LaTeX body across one or more lines. ``$...$`` is inline,
# ``\[ ... \]`` is display.
INSET_BEGIN = "\\begin_inset Formula"
INSET_END = "\\end_inset"


@dataclass
class Formula:
    body: str          # raw LaTeX between the delimiters
    line_no: int       # 1-based line number of the begin marker


def extract_formulas(lines: List[str]) -> List[Formula]:
    """Find every Formula inset in a LyX file's lines and return the
    LaTeX bodies. Whitespace inside the body is preserved."""
    formulas: List[Formula] = []
    i = 0
    while i < len(lines):
        line = lines[i].rstrip("\n")
        if line.startswith(INSET_BEGIN):
            # The header is followed by lines containing the formula
            # body until the matching ``\\end_inset``.
            begin_line = i + 1
            i += 1
            body_lines: List[str] = []
            while i < len(lines):
                cur = lines[i].rstrip("\n")
                if cur.startswith(INSET_END):
                    break
                body_lines.append(cur)
                i += 1
            body = "\n".join(body_lines).strip()
            # Strip the surrounding ``$`` or ``\\[ ... \\]`` delimiters
            # so the body is bare LaTeX.
            body = _strip_math_delimiters(body)
            if body:
                formulas.append(Formula(body=body, line_no=begin_line))
        i += 1
    return formulas


def _strip_math_delimiters(s: str) -> str:
    s = s.strip()
    if s.startswith("$") and s.endswith("$"):
        return s[1:-1].strip()
    if s.startswith("\\[") and s.endswith("\\]"):
        return s[2:-2].strip()
    return s


def emit_cpp(formulas: List[Formula], namespace: str) -> str:
    """Emit a C++ snippet that uses the ``_tex`` UDL on every extracted
    formula. The snippet declares an anonymous lambda per formula so
    they can be copy-pasted into a translation unit."""
    out: List[str] = [
        "// Generated by lyx_to_tex.py from a LyX document.",
        "// Each block below corresponds to one Formula inset.",
        "#include <tensor/tex/tex.hpp>",
        "",
        f"using namespace {namespace};",
        "",
    ]
    for idx, f in enumerate(formulas, start=1):
        out.append(f"// Formula #{idx} (LyX line {f.line_no}):")
        # Use a raw string with a unique delimiter to avoid clashes with
        # any closing parens the formula body might contain.
        delim = _safe_raw_delimiter(f.body)
        out.append(f'auto formula_{idx} = R"{delim}({f.body}){delim}"_tex;')
        out.append("")
    return "\n".join(out)


def _safe_raw_delimiter(body: str) -> str:
    """Pick a raw-string delimiter that does not appear in the body."""
    for candidate in ("", "lyx", "tex", "tensor", "raw"):
        sentinel = f"){candidate}\""
        if sentinel not in body:
            return candidate
    raise RuntimeError("could not find a safe raw-string delimiter")


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="Path to the LyX document")
    parser.add_argument(
        "--namespace",
        default="tensor::tex::literals",
        help="C++ namespace whose `_tex` UDL is brought in via `using namespace`",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Write the emitted C++ to this path (default: stdout)",
    )
    args = parser.parse_args(argv)

    if not args.input.exists():
        print(f"error: {args.input} does not exist", file=sys.stderr)
        return 2

    formulas = extract_formulas(args.input.read_text().splitlines(keepends=True))
    if not formulas:
        print("warning: no Formula insets found", file=sys.stderr)

    snippet = emit_cpp(formulas, args.namespace)
    if args.output:
        args.output.write_text(snippet)
    else:
        print(snippet)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
